### ISSUE TITLE
`system` is both a Cascade keyword and an object class

### ISSUE THREAD

**Issue by dburgener** [dburgener/cascade#59]
A rule like:

```
allow(this, foo, system, [start]);
```

Fails to compile currently, because `system` is parsed as the reserved keyword rather than some arbitrary string that will later be consumed as a valid object class.

**Comment by dburgener** [comment]
I wonder if `policy` would be a decent keyword to replace the Cascade `system` keyword and address this?  @matt-sheets @l0kod what do you think?

**Comment by matt-sheets** [comment]
I like that.  When I was dealing previously with different policy binaries produced from the same source (mls, target, etc) I would refer to them as different policies.

And just to throw in another contender if we need one, `platform`

**Comment by dburgener** [comment]
I started renaming to "policy", and quickly ran into this comment: https://github.com/dburgener/cascade/blob/39c886431abfe43a20d3ab652c1d721859e77505/src/compile.rs#L291

I feel like the simple search/replace approach here creates a confusing comment, since "policy" could equally refer to all the policy present in the source repo, rather than what is intended here, which is "the subset of policy being built in a particular "policy"".  Which makes me think that this would be somewhat overloading the term policy.  It's not a functional problem in the same way that overloading "system" is now, but it does seem somewhat confusing.

"platform" seems less overloaded and might be a better idea in that case.  I'm less enthusiastic for vague hard to articulate aesthetic reasons, but if it avoids confusion, that's good.

Am I overreacting about the potential confusion of using "policy" here?

**Comment by dburgener** [comment]
@matt-sheets What about "machine"? (Suggested-by: @pebenito)

**Comment by matt-sheets** [comment]
machine works for me

**Comment by dburgener** [comment]
Okay, I'll work on a PR to do the full rename to "machine".
